### ISSUE TITLE
Error with poetry 1.1.3 and Python 3.7

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/cookiecutter-hypermodern-python#629]
With the release of the template 2020.10.15, the `tests` and `mypy` sessions are failing with Python 3.7.
You can see it with the [PR #338 on cookiecutter-hypermodern-python-instance](https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/338).

This seems related to a regression in export function in poetry 1.1.X. There are already a discussion on the topic and I've share this issue in the [issue #3160 on poetry repository](https://github.com/python-poetry/poetry/issues/3160#issuecomment-711157947)

On my repositories using the cookiecutter template i will downgrade poetry to 1.0.10

**Comment by staticdev** [comment]
@oncleben31 this one is now fixed on 2021.1.29.

**Comment by cjolowicz** [comment]
It should be noted though that the underlying bug in Poetry is still present. Dependencies may be installed without the version pin from poetry.lock. Due to changes in nox-poetry, this no longer results in an error due to missing hashes. (nox-poetry no longer generates the hashes, because the new pip resolver does not fully support hashes in constraints files.)

**Comment by cjolowicz** [comment]
AFAIU there's nothing left to do here (please correct me if this still affects you).
